##  아래 Cell은 각 PC마다 다른 숫자(Hash값)를 생성시키는 Program입니다.
### 실행 ( Run ) 시켜 주십시요...

In [2]:
from uuid import getnode as get_mac
mac = get_mac()
mac_addr=str(mac)
import hashlib
hash_object= hashlib.sha1(mac_addr.encode('utf-8'))
signature = int(hash_object.hexdigest(), 16) % 10**8
print(str(signature))

6824137


In [3]:
import numpy as np

In [5]:
L = [1,2,3,4,5,6,7,8,9]
a = np.array(L)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c= b*10+4
c

array([[14, 24, 34],
       [44, 54, 64],
       [74, 84, 94]])

In [8]:
a.dtype

dtype('int64')

In [9]:
d= np.array([1.1,2,3,4])
d

array([1.1, 2. , 3. , 4. ])

In [10]:
d.dtype

dtype('float64')

In [11]:
e=np.array([1.1,2,3,4],dtype =np.float32)
e.dtype

dtype('float32')

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr = a.reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
arr[0:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr[2,1:]

array([11, 12, 13, 14])

In [28]:
arr[:2,2:4]

array([[2, 3],
       [7, 8]])

In [29]:
arr[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [30]:
arr[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [31]:
arr.sum()

105

In [34]:
arr.sum(axis =0 )

array([15, 18, 21, 24, 27])

In [35]:
arr.sum(axis=1)

array([10, 35, 60])

In [36]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c=a[3:7]
c

array([3, 4, 5, 6])

In [38]:
c[:]=0
c

array([0, 0, 0, 0])

In [39]:
a

array([0, 1, 2, 0, 0, 0, 0, 7, 8, 9])

In [40]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [42]:
a+b

array([ 5,  7,  9, 11, 13])

In [43]:
b-a

array([5, 5, 5, 5, 5])

In [44]:
a**2

array([ 0,  1,  4,  9, 16])

In [45]:
a>3

array([False, False, False, False,  True])

In [46]:
10*np.sin(a)

array([ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [47]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [48]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [50]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [51]:
at = a.T
at

array([[0, 2],
       [1, 3]])

In [54]:
b=np.array([[0,1],[1,1]])
b

array([[0, 1],
       [1, 1]])

In [55]:
np.dot(a,b)

array([[1, 1],
       [3, 5]])

In [57]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [59]:
c=a+10
c

array([10, 11, 12, 13, 14])

In [60]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
b=np.array([[10],[20],[30]])
b

array([[10],
       [20],
       [30]])

In [62]:
a+b

array([[10, 11],
       [22, 23],
       [34, 35]])

In [65]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [66]:
x+b

array([[10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [67]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
np.save('a_data.npy',a)

In [69]:
import os
os.getcwd()

'/home/infocom/다운로드'

In [70]:
b=np.load('a_data.npy')
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
np.savetxt('a_txt',a)

In [74]:
b= np.loadtxt('a_txt')
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [75]:
b.dtype

dtype('float64')

In [76]:
import numpy.linalg as nl

In [78]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [79]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [82]:
nl.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [83]:
y=np.array([5.0,7.0])

In [84]:
nl.solve(a,y)

array([-3.,  4.])