##  아래 Cell은 각 PC마다 다른 숫자(Hash값)를 생성시키는 Program입니다.
### 실행 ( Run ) 시켜 주십시요...

In [1]:
from uuid import getnode as get_mac
mac = get_mac()
mac_addr=str(mac)
import hashlib
hash_object= hashlib.sha1(mac_addr.encode('utf-8'))
signature = int(hash_object.hexdigest(), 16) % 10**8
print(str(signature))

6824137


In [3]:
import numpy as np

### Quiz 1 numpy  method만을 사용해서 아래 보기와 같은  array를 생성하시요

A = array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
A= np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
A.reshape((4,4))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Quiz 2  아래 보기와 같은 array를 생성하시요 (Hint : Broadcasting 기능을 사용)
A = array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [25]:
x=np.array([10,20,30])
y=np.array([[1],[2],[3],[4]])
x+y

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

### Quiz 3
 - 아래 2 dimension array A로부터 slice / stride를 사용해서 B array를 만들어 내시요...

- A = array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
       

- B = array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18]])
       


In [43]:
A = np.array([[ 0, 1, 2, 3, 4],

 [ 5,  6,  7,  8,  9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]])
B=A[::1,::3]
B

array([[ 0,  3],
       [ 5,  8],
       [10, 13],
       [15, 18],
       [20, 23]])

### Quiz 4 

아래 2개의 2-d array  (A, B)를 이용해서  제 3의 array를 만드세요.. (반드시 numpy array를 사용)  

In [3]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [4]:
B = np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

###    아래 C array를 만드세요

C = array([[0, 1, 4, 5],
       [2, 3, 6, 7]])


In [36]:
C=hstack([A,B])

NameError: name 'hstack' is not defined